### ISSUE TITLE
Please Add the default value for HttpsPort and IISExpressHttpsPort to the Api and GraphQL Templates

### ISSUE THREAD

**Issue by awright18** [Dotnet-Boxed/Templates#1099]
In the [Api Template](https://github.com/Dotnet-Boxed/Templates/blob/main/Source/ApiTemplate/.template.config/template.json)

The HttpPort has a default value set to 5000. 

https://github.com/Dotnet-Boxed/Templates/blob/b69bc5be2fd32bb8ae2146de62c882138459a8c5/Source/ApiTemplate/.template.config/template.json#L444-L449

For the HttpsPort parameter, the default value is not specified although there is a fallback value of 5001.  Could the default value be specified, please? 

https://github.com/Dotnet-Boxed/Templates/blob/b69bc5be2fd32bb8ae2146de62c882138459a8c5/Source/ApiTemplate/.template.config/template.json#L466-L470

May I also ask the same for the IISExpressHttpsPort?  Its value is 44300 in your template.

https://github.com/Dotnet-Boxed/Templates/blob/b69bc5be2fd32bb8ae2146de62c882138459a8c5/Source/ApiTemplate/.template.config/template.json#L487-L491

The same applies to the GraphQL template.  I'd be happy to open a PR if this issue is approved.

**Comment by RehanSaeed** [comment]
Thanks for raising.

Fixed in https://github.com/Dotnet-Boxed/Templates/pull/1102.
