### ISSUE TITLE
install command refuses  to install templates 

### ISSUE THREAD

**Issue by clmcgrath** [Dotnet-Boxed/Templates#1133]
### Actual behaviour 

after running `dotnet install Boxed.Templates` several times ,  the templates refuse to show up in the `dotnet new ` list 

### Expected behaviour

the templates to be installed after running `dotnet install Boxed.Templates`

### Project template
Affecting all templates 

## Environment
dotnet core 3.1, dotnet 5  windows 10

**Comment by RehanSaeed** [comment]
Seems to be working for me. You can try `dotnet new --debug:reinit` to reset `dotnet new` and see if that solves the issue.

**Comment by clmcgrath** [comment]
seems to be ok from my office machine will try that on my laptop when i get a chance

**Comment by RehanSaeed** [comment]
Feel free to reopen if you still have an issue.
