### ISSUE TITLE
Cluster fixture is disposed and initialized for every test/fact in a class. 

### ISSUE THREAD

**Issue by oising** [Dotnet-Boxed/Templates#1184]
Take CounterGrainTest.cs for example -- it has two tests. Debug them, and attach a breakpoint on clusterfixture DisposeAsync/InitalizeAsync -- the cluster is destroyed and recreated for each test. This seems like a mistake :)

**Comment by oising** [comment]
Ah, it seems this is expected from the perspective of xunit -- but is this really the best default behaviour for a boxed template? It seems we could benefit from using a class fixture. 

https://github.com/xunit/xunit/issues/2099

**Comment by oising** [comment]
Down the rabbit hole I went, and finally hit this: https://github.com/xunit/xunit/issues/565

So it's just not possible to inject the helper into a fixture for a shared context. This is dumb as a bag of hair. Sigh.

**Comment by RehanSaeed** [comment]
Hey @oising! I agree that the speed of running these tests is not ideal. Another problem with running tests with the same cluster is that you then have to deal with resetting the cluster before each test.

If there is a better way to do this, I'd be really happy to learn it!
