### ISSUE TITLE
Improve testing

### ISSUE THREAD

**Issue by AlirezaHaghshenas** [Dotnet-Boxed/Templates#1199]
### Describe the feature

The Graphql integration tests project misses a lot of the configuration. For instance, if we read the connectionstring from user secrets file, that will be missing here. Also, while the returned json in development mode is indented, the one that is returned in test setup is compact. I changed `Source/TezGraph/MvcBuilderExtensions.cs` to:

```
                    if (webHostEnvironment.IsDevelopment() ||
                        webHostEnvironment.IsEnvironment(Constants.EnvironmentName.Test))
                    {
                        // Pretty print the JSON in development for easier debugging.
                        options.SerializerSettings.Formatting = Formatting.Indented;
                    }
```
But I still get a compact json in my snapshot tests.

Finally, in generated tests, there is no test that calls a graphql query and users of this template have to figure that out by themselves.

So my suggestion is:

1. Modify the test setup to have minimal differences from development, and somehow have these differences explicitly visible to the developer.
2. Add a sample test that calls a graphql query and verifies the result (probably against a snapshot)

### Project Template

graphql

**Comment by AlirezaHaghshenas** [comment]
OK. I made a mistake: even in development, the response is not indented.

So a side question is: how should we configure the response to be indented? Isn't the line `options.SerializerSettings.Formatting = Formatting.Indented;` supposed to do that?

**Comment by RehanSaeed** [comment]
```cs
                    if (webHostEnvironment.IsDevelopment() ||
                        webHostEnvironment.IsEnvironment(Constants.EnvironmentName.Test))
                    {
                        // Pretty print the JSON in development for easier debugging.
                        options.SerializerSettings.Formatting = Formatting.Indented;
                    }
```

This is a good change to make for the templates, want to submit a PR for the API and GraphQL projects?

> Add a sample test that calls a graphql query and verifies the result (probably against a snapshot)

This is the intention. Hot Chocolate has some improvements to testing coming in v12 that I was hoping to use.

**Comment by RehanSaeed** [comment]
> So a side question is: how should we configure the response to be indented? Isn't the line options.SerializerSettings.Formatting = Formatting.Indented; supposed to do that?

This should work.

**Comment by RehanSaeed** [comment]
It seems its not possible in Hot Chocolate just yet, see https://github.com/ChilliCream/hotchocolate/issues/4072. Removed the customization for now in https://github.com/Dotnet-Boxed/Templates/pull/1220.
