### ISSUE TITLE
Disabling Docker Leaves Cake File with No Default Task

### ISSUE THREAD

**Issue by RehanSaeed** [Dotnet-Boxed/Templates#1313]
### Describe the bug

Dotnet templating engine does not support conditionl uncommenting in `.cake` files:

- https://github.com/dotnet/templating/issues/4070

### Steps to reproduce

1. `dotnet new api --docker=false`
2. Check `build.cake`
3. See default task is still commented out.
```
//Task("Default")
//    .Description("Cleans, restores NuGet packages, builds the solution, runs unit tests and then publishes.")
//    .IsDependentOn("Build")
//    .IsDependentOn("Test")
//    .IsDependentOn("Publish");
```

**Comment by andigokas** [comment]
oh

**Comment by RehanSaeed** [comment]
> 
> 
> oh

You can just uncomment it to fix it. Issue is fixed in https://github.com/Dotnet-Boxed/Templates/pull/1309.
