### ISSUE TITLE
Unable to access health checks with Orleans template.

### ISSUE THREAD

**Issue by ElanHasson** [Dotnet-Boxed/Templates#1427]
### Describe the bug

Health check routes are inaccessible in the Orleans template.

### Steps to reproduce

Make a new project and observe the 404 for /status and /status/self

### Expected behaviour

Healthy should be returned.

### Template

Orleans

### .NET Boxed Version

Latest

### Visual Studio Version

Visual Studio 2022

### .NET Version

.NET 6

**Comment by RehanSaeed** [comment]
Thank you for raising this bug. The health check is actually available at `http://localhost:5000/status`.

**Comment by RehanSaeed** [comment]
Fixed in https://github.com/Dotnet-Boxed/Templates/pull/1429.

**Comment by ElanHasson** [comment]
Ahh! @RehanSaeed that makes sense too since OrleansDashboard has it's setup internally! 
Thank you!
