### ISSUE TITLE
Include `xunit.analyzers`

### ISSUE THREAD

**Issue by JamieMagee** [Dotnet-Boxed/Templates#1695]
### Describe the feature

Alongside xunit's 2.4.2 release yesterday, xunit.analyzers 1.0.0 was also released. I think it would be a good addition to the templates.

### Project Template

All

**Comment by RehanSaeed** [comment]
It's included in the base xunit package:

![image](https://user-images.githubusercontent.com/2270364/182431544-6fe43980-8268-4420-9406-9b64e404f563.png)
