### ISSUE TITLE
Donet Cake DockerBuild does not fail the GH action step 

### ISSUE THREAD

**Issue by ElanHasson** [Dotnet-Boxed/Templates#1704]
### Describe the bug

Donet Cake DockerBuild does not fail the GH action step in event of errors.

<img width="1173" alt="image" src="https://user-images.githubusercontent.com/234704/183526438-758bd706-b466-44b0-9f4c-84b14bada1df.png">

### Steps to reproduce

1. Produce an image that throws an error

### Expected behaviour

Should fail the step.

### Template

Orleans, have seen with others that use DockerBuild

### .NET Boxed Version

7.13.4 

### Visual Studio Version

GitHub Actions

### .NET Version

.NET 6

**Comment by ElanHasson** [comment]
@RehanSaeed this is a different issue.

When the build fails within the service's dockerfile build, the exit code is swallowed by cake I'm assuming.

Please reopen.

**Comment by ElanHasson** [comment]
Here is an example: https://github.com/web-scheduler/web-scheduler-api/runs/7897764448?check_suite_focus=true#step:10:146

`dotnet build` failed with errors, but the GH build task succeeded. It may have to do with a change I've made to cake, but it is unclear.

**Comment by RehanSaeed** [comment]
I'll investigate soon.
