### ISSUE TITLE
Add ASP.NET Core 2.2 Health Checks

### ISSUE THREAD

**Issue by RehanSaeed** [Dotnet-Boxed/Templates#194]
Use the ASP.NET Core 2.2 health checks. Waiting for it to be released.

**Comment by VictorioBerra** [comment]
Can you provide a link to the 2.2 Health Checks? Do you mean [this](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/implement-resilient-applications/monitor-app-health)?

**Comment by RehanSaeed** [comment]
Looks like it was released "out of band" and without any fanfare (as far as I'm aware). The GitHub page for the project suggests that the API is still evolving. According to this thread, it will be in 2.2 officially:

https://github.com/dotnet-architecture/HealthChecks/issues/34

**Comment by RehanSaeed** [comment]
Fixed in the 1.11.0 release.
