### ISSUE TITLE
Add subscriptions backplane (using Signal-R?)

### ISSUE THREAD

**Issue by RehanSaeed** [Dotnet-Boxed/Templates#198]
If you deploy the current template to multiple servers, the subscriptions will not work. We need a backplane, so that each instance of the GraphQL server is aware of any changes and can raise subscription events.

**Comment by RehanSaeed** [comment]
See https://github.com/graphql-dotnet/server/issues/135

**Comment by RehanSaeed** [comment]
See https://github.com/graphql-dotnet/graphql-dotnet/issues/705

**Comment by RehanSaeed** [comment]
Switching to Hot Chocolate GraphQL. It uses Redis, so this is not needed anymore.

**Comment by drudolph1** [comment]
I would like to see a subscriptions backplane using Signal R. Is there any hope for this being done?
