### ISSUE TITLE
Extension gallery entry image problem

### ISSUE THREAD

**Issue by Jogai** [Dotnet-Boxed/Templates#206]
The page about ASP.NET Core MVC 6 extension in the gallery does not show the images that belong to it: https://visualstudiogallery.msdn.microsoft.com/6cf50a48-fc1e-4eaf-9e82-0b2a6705ca7d

**Comment by RehanSaeed** [comment]
Fixed. The MVC 5 template in the Visual Studio Extension is no longer supported but still available and working.
