### ISSUE TITLE
All the stuff in the web config, and NWebSec

### ISSUE THREAD

**Issue by VictorioBerra** [Dotnet-Boxed/Templates#209]
﻿**Which project template is the issue about?**
API
...

If I do not use IIS/IIS Express will the stuff in the web config still be used by Kestrel?

Also, I removed the NWebSec packages and built my project without errors, what are they for exactly?

**Comment by RehanSaeed** [comment]
No, that is a bug. That file should be removed if IIS is not selected.

**Comment by RehanSaeed** [comment]
At one point I was using NWebSec for setting the HSTS HTTP header, ASP.NET Core has middleware for that built in now, so it's not needed.

**Comment by RehanSaeed** [comment]
It turns out the file was being removed when the IIS option was deselected.

It also turns out that when 2.0 was released, they changed the way that web.config was generated/modified. I've updated the file after reading the ASP.NET Core docs. This will go out in the next version.
