### ISSUE TITLE
Remove Serilog.Extensions.Logging

### ISSUE THREAD

**Issue by VictorioBerra** [Dotnet-Boxed/Templates#211]
https://github.com/serilog/serilog-extensions-logging#aspnet-core-20-instructions

### ASP.NET Core 2.0+ Instructions

**ASP.NET Core 2.0** applications should prefer [Serilog.AspNetCore](https://github.com/serilog/serilog-aspnetcore) and `UseSerilog()` instead.

**Comment by RehanSaeed** [comment]
Thanks for raising these bugs. Things are cleaning up nicely.

**Comment by RehanSaeed** [comment]
Fixed BTW.

**Comment by RehanSaeed** [comment]
Released soonish.
