### ISSUE TITLE
Cursor Issue?

### ISSUE THREAD

**Issue by penleychan** [Dotnet-Boxed/Templates#213]
Hello,

I am trying out the GraphQL template with the pagination, however I am getting an error when trying out the example.

Query: 
```
{
  droids(first: 10, after: "MzAwMy0wMy0wMQ==") {
    items{
      name,
      created
    }
  }
}
```
Where `MzAwMy0wMy0wMQ==` is `3003-03-01`

Error message: 

> "message": "GraphQL.ExecutionError: Error trying to resolve droids. ---> System.ArgumentOutOfRangeException: startIndex cannot be larger than length of string.\r\nParameter name: startIndex\r\n   at System.String.Substring(Int32 startIndex, Int32 length)\r\n   at boxed_template.Cursor.FromNullableCursor[T](String cursor) in C:\\src\\boxed-template\\Cursor.cs:line 41\r\n   at boxed_template.Schemas.QueryObject.ResolveConnection(IDroidRepository droidRepository, ResolveConnectionContext`1 context) in C:\\src\\boxed-template\\Schemas\\QueryObject.cs:line 94\r\n   at GraphQL.Execution.ExecutionHelper.UnwrapResultAsync(Object result)\r\n   at GraphQL.Execution.ExecutionStrategy.ExecuteNodeAsync(ExecutionContext context, ExecutionNode node)\r\n   --- End of inner exception stack trace ---"

If I remove `.Substring(Prefix.Length + 1)` from `var value = Base64Decode(cursor).Substring(Prefix.Length + 1);` on the method for `public static T? FromNullableCursor<T>(string cursor)` it works fine.

Am I misunderstanding something with the cursor? Is `.Substring(Prefix.Length + 1)` suppose to be used?

Thanks.

**Comment by RehanSaeed** [comment]
I haven't forgot about this issue, I've been busy with the 2.1.1 release and learning Kubernetes.

I need to write some unit tests for the Cursor class to make sure it's rock solid.

**Comment by RehanSaeed** [comment]
Check the latest commits today for some updates where I added some code to handle this better.

The Cursor prefixes the data with `arrayconnection:` then base 64 encodes the data. So in your case it should be `arrayconnection:3003-03-01`.
