### ISSUE TITLE
F# templates

### ISSUE THREAD

**Issue by xperiandri** [Dotnet-Boxed/Templates#214]
I'm going to handle this at some time

**Comment by xperiandri** [comment]
No, I just want regular ASP.NET Core with F#
Even using it without specific experience in functional programming can reduce the amount of redundant code. So just having your templates in F# would be pretty nice.
And Girrafe does not friend with GraphQL yet. It is a good point of enhancement

**Comment by RehanSaeed** [comment]
Interesting. Are you willing to keep any F# templates up to date and port new C# features to F#?

**Comment by xperiandri** [comment]
Yes, they will be nearly the same templates as you have for C#. Like ASP.NET Core F# template which is almost the same as C# one.

**Comment by RehanSaeed** [comment]
Closing for now. Feel free to reopen if there are new developments.

**Comment by xperiandri** [comment]
Why? Someone will pick it up

**Comment by RehanSaeed** [comment]
Unfortunately, I don't have time to learn F# and maintain it, my resources are finite. If someone is willing to join the project and put in as much time as I put in for C# templates, then maybe we can talk. I'll leave it open to see if someone sees it as you suggest.

**Comment by RehanSaeed** [comment]
It's been a year and a half. I don't see us doing this. I also want to keep the number of templates low, so they can be maintained. Closing for now but if anyone wants to add an F# template, add a comment.

**Comment by xperiandri** [comment]
Well I just now finishing my F# GraphQL + Cosmos DB project and wanted to create a template based on it

**Comment by xperiandri** [comment]
Waiting for @johnberzy-bazinga to release an updated package

**Comment by xperiandri** [comment]
Of https://github.com/fsprojects/FSharp.Data.GraphQL/

**Comment by RehanSaeed** [comment]
That seems cool. I myself was just about to start work on porting the GraphQL project template to Hot Chocolate which seems like a more complete library with better docs too.

I suggest getting it ready and then we can talk about adding it in a new issue. If you have something to look at that would be nice too (although I'm no F# expert).

**Comment by xperiandri** [comment]
@RehanSaeed we finally come to the point when we can make GraphQL template in F#.
Where should we put them?

**Comment by xperiandri** [comment]
Also, I'm going to add F# specific stuff to .editorconfig template. OK?

**Comment by RehanSaeed** [comment]
I have a separate repo for `.editorconfig` at https://github.com/RehanSaeed/EditorConfig. Please raise an issue there explaining what is lacking for F#.

Can you outline what packages etc. you plan to use for this project? Is it based on https://github.com/fsprojects/FSharp.Data.GraphQL/? How does that project compare feature wise to Hot Chocolate? I have a work in progress PR up now to switch to that.

**Comment by xperiandri** [comment]
Yes, it will be https://github.com/fsprojects/FSharp.Data.GraphQL/
I planned that the template will be the same in functionality as your template in C#. As an option user will be able to enable SQRS.
Maybe we will also introduce an option to use Azure Cosmos as storage.

``` XML
<PackageReference Include="Dahomey.Json" Version="1.10.3" />
<PackageReference Include="FSharp.Control.AsyncSeq" Version="2.0.24" />
<PackageReference Include="FSharp.Control.FusionTasks" Version="2.0.2" />
<PackageReference Include="FSharp.Control.Reactive" Version="4.5.0" />
<PackageReference Include="FSharp.Data.GraphQL.Server" Version="1.0.7" />
<PackageReference Include="FSharp.Data.GraphQL.Server.Middleware" Version="1.0.7" />
<PackageReference Include="FSharp.SystemTextJson" Version="0.15.14" />
<PackageReference Include="FSharpx.Extras" Version="2.5.0" />
<PackageReference Include="FsToolkit.ErrorHandling" Version="2.0.0" />
```

**Comment by xperiandri** [comment]
So can we take hot-chocolate branch and work from it?

**Comment by RehanSaeed** [comment]
For v1, I'd consider adding something very basic. Storage could be an optional feature added later. Not everyone wants to use Azure Cosmos.

The Hot Chocolate branch is broken, we were waiting for Hot Chocolate v11 to be released which it has done. Just need to upgrade to that and complete it. So please don't use it as a base.

**Comment by xperiandri** [comment]
So how will we split folders? Where do I need to put my F# template?
