### ISSUE TITLE
IIS Express not working with a fresh project

### ISSUE THREAD

**Issue by senneclaeskens** [Dotnet-Boxed/Templates#233]
﻿**Which project template is the issue about?**
ASP.NET Core API Boxed

**Which version of the project template is the issue about?**
1.10.0

**Which version of Visual Studio or the dotnet SDK were you using?**
VS2017 15.9.2
SDK 2.1.500

When I run the project, using the IIS Express settings, I get an error:

![vs](https://user-images.githubusercontent.com/6286010/49106229-e8311080-f282-11e8-8f47-2660959269b5.PNG)

Details of the error:

![image](https://user-images.githubusercontent.com/6286010/49106251-faab4a00-f282-11e8-8e7a-c1d75a85c260.png)

It's related to the following:
Config Error | Lock violation

When I edit the applicationconfig.host and remove lockitem="true" for all system.webServer > modules, I get a different error.

![image](https://user-images.githubusercontent.com/6286010/49106359-465df380-f283-11e8-8b81-30bf1addf2d3.png)

Am I missing something? When I remove the <modules> section in web.config, everything works fine.

Thanks for your time and sorry if this an issue on my part. Great template btw!

**Comment by RehanSaeed** [comment]
Fixed in the 2.2 update. See the release notes for more info,
