### ISSUE TITLE
Update to Core 2.2

### ISSUE THREAD

**Issue by VictorioBerra** [Dotnet-Boxed/Templates#243]
- [x] Add `<AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>` to .csproj(s). It is now the default.
- [x] Use built-in health checker.
- [x] Use options validation.

I am sure there are other things.

**Comment by RehanSaeed** [comment]
Adding options validation is also in that list.

Working on this now.

**Comment by RehanSaeed** [comment]
Nearly there.

**Comment by RehanSaeed** [comment]
Done. Will sort out a release soon.

**Comment by RehanSaeed** [comment]
Need to sort out https://github.com/Dotnet-Boxed/Templates/issues/233 first.
