### ISSUE TITLE
Replace exception middleware with ProblemDetails middleware?

### ISSUE THREAD

**Issue by VictorioBerra** [Dotnet-Boxed/Templates#247]
[The latest version of MVC 2.2 introduces problem details.](https://docs.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-2.2?view=aspnetcore-2.2#problem-details-support)

> ASP.NET Core 2.1 introduced `ProblemDetails`, based on the RFC 7807 specification for carrying details of an error with an HTTP Response. In 2.2, `ProblemDetails` is the standard response for client error codes in controllers attributed with `ApiControllerAttribute`. An `IActionResult` returning a client error status code (4xx) now returns a `ProblemDetails` body. The result also includes a correlation ID that can be used to correlate the error using request logs. For client errors, `ProducesResponseType` defaults to using `ProblemDetails` as the response type. This is documented in Open API / Swagger output generated using NSwag or Swashbuckle.AspNetCore.

We may want to update our Swagger docs, and more to properly utilize this. This brings me to middlware:

https://github.com/khellang/Middleware/

Specifically https://github.com/khellang/Middleware/blob/master/src/ProblemDetails/ProblemDetailsMiddleware.cs

Some else has a good package for this. We may want to use this instead of our hand rolled one in [Framework](https://github.com/Dotnet-Boxed/Framework/).

**Comment by RehanSaeed** [comment]
Problem Details is now the default in ASP.NET Core 2.2, so no need for that middleware which I've been aware of for some time. I've checked in some changes to make Problem Details work nicely yesterday.

The only thing missing is to provide an example JSON in Swagger's documentation for all the 4xx responses.

Just seen your comments in https://github.com/khellang/Middleware/issues/39 ........maybe we should add the middleware. Not sure yet, don't want to add another dependency just for that.

**Comment by RehanSaeed** [comment]
Will stick with not adding the dependency for now. What are your thoughts on adding it for 500 errors?

**Comment by VictorioBerra** [comment]
I mainly use it now so I can still throw errors like 404 and 400 deep inside of my code. Some services/extension methods I do not want to return an ActionResult<T> so instead I can `throw new ProblemDetailsException()` and set the status code to whatever I want.

**Comment by RehanSaeed** [comment]
Closing for now, will keep an eye on this.
