### ISSUE TITLE
[Request] Call ConfigureKestrel instead of UseKestrel

### ISSUE THREAD

**Issue by JaeWangL** [Dotnet-Boxed/Templates#248]
from
https://docs.microsoft.com/en-us/aspnet/core/migration/21-to-22?view=aspnetcore-2.2&tabs=visual-studio

**Comment by RehanSaeed** [comment]
Thanks for the link. The 2.2 upgrade is in progress. Mostly done. Will release sometime after Christmas.

**Comment by RehanSaeed** [comment]
BTW, you only need to do that if you use `CreateDefaultBuilder`.
