### ISSUE TITLE
HttpContextAccessor is null

### ISSUE THREAD

**Issue by senneclaeskens** [Dotnet-Boxed/Templates#256]
﻿**Which project template is the issue about?**

ASP.NET Core API Boxed

**Which version of the project template is the issue about?**

1.11.0

**Which version of Visual Studio or the dotnet SDK were you using?**

VS2017 15.9.4
SDK 2.2.101

HttpContextAccessor is null. 

![image](https://user-images.githubusercontent.com/6286010/50643484-914be480-0f6e-11e9-9714-f8d915073f2a.png)

I assume this is not really related to the template, but I just wanted to give a heads-up. I will investigate further and see where it's coming from.

**Comment by RehanSaeed** [comment]
Thanks for this. It's weird that the `IHttpContextAccessor` is returning a `null` `HttpContext`.

I'll write a test to make sure I catch this for the future.

**Comment by RehanSaeed** [comment]
This is the problem: https://github.com/aspnet/AspNetCore/issues/5144

**Comment by RehanSaeed** [comment]
Fixed in https://github.com/Dotnet-Boxed/Templates/commit/b041d0e54b6a0fe4e777381ec76efce9e8e9c63b

**Comment by VictorioBerra** [comment]
That was fast! 😱

**Comment by RehanSaeed** [comment]
Released https://github.com/Dotnet-Boxed/Templates/releases/tag/Boxed.Templates.1.11.1

**Comment by RehanSaeed** [comment]
Added test, so this doesn't happen again in https://github.com/Dotnet-Boxed/Templates/commit/c7d701b7e302b046e034a9f652546e31f85863b3.

Thanks for reporting! Have a nice day!

**Comment by senneclaeskens** [comment]
Great, thanks a lot! Didn't have time yet to investigate it myself!
