### ISSUE TITLE
README looked broken on API

### ISSUE THREAD

**Issue by VictorioBerra** [Dotnet-Boxed/Templates#257]
https://github.com/Dotnet-Boxed/Templates/tree/master/Source/Content/ApiTemplate

Looks like github isnt rendering the ReadMe.html?

**Comment by RehanSaeed** [comment]
Any ideas why? Seems weird.

**Comment by VictorioBerra** [comment]
Not sure, I didnt even know you could use an HTML file instead of an MD file.
