### ISSUE TITLE
Graphql readme update needed

### ISSUE THREAD

**Issue by dev-aritra** [Dotnet-Boxed/Templates#267]
Thank you for the awesome templates, I believe this would make life easier for a lot of people.

Currently the readme for both the template is 
**Run dotnet new api --help to see how to select the feature of the project.
Run dotnet new api --name "MyTemplate" along with any other custom options to create a project from the template.**

Where as this holds for the `ASP.NET Core API Boxed` project.
But for the GraphQL template shouldn't it be 
**Run dotnet new _graphql_ --help to see how to select the feature of the project.
Run dotnet new _graphql_ --name "MyTemplate" along with any other custom options to create a project from the template.**

As the short name for the GraphQL template is "_graphql_".

**Comment by RehanSaeed** [comment]
Fixed. Thank you!
