### ISSUE TITLE
Publish site and can't run with Kestrel

### ISSUE THREAD

**Issue by xgluxv** [Dotnet-Boxed/Templates#284]
**ASP.NET Core API Boxed**
**Boxed Templates 1.14.0**
**dotnet SDK 2.2**
I use dotnet new api --name "tempApi" create site app, and publish it. but when I run it with dotnet tempApi.dll command. An error has occurred: System.FormatException: Invalid url: 'http:////*:80'
![2019-03-04 212118](https://user-images.githubusercontent.com/147598/53736346-66c1cd80-3ec4-11e9-8a29-af3f08f3264c.jpg)

**Comment by RehanSaeed** [comment]
Thanks for reporting. Fixed in the version being released soon. In appsettings.production.json you need to remove the quadruple slash so it looks like this:

```
"Kestrel": {
    "Endpoints": {
      //#if (HttpsEverywhere)
      "Https": {
        "Url": "https://*:443",
        "Certificate": {
          // TODO
        }
      },
      //#endif
      "Http": {
        "Url": "http://*:80"
      }
    }
  },
```
