### ISSUE TITLE
appsettings ignored for EnableMetrics on GraphQL

### ISSUE THREAD

**Issue by bppn** [Dotnet-Boxed/Templates#286]
﻿**Which project template is the issue about?**

GraphQL boxed template

**Which version of the project template is the issue about?**

Latest version

**Which version of Visual Studio or the dotnet SDK were you using?**

Visual Studio 2017 Professional

Regardless of the setting in appsettings.json, the EnableMetrics is always true when debugging.  Settings like MaxDepth are read correctly.

**Comment by RehanSaeed** [comment]
Thanks for reporting, fixed in the next release coming in a few minutes.
