### ISSUE TITLE
Generate unit-test project for the template. 

### ISSUE THREAD

**Issue by lamLeX** [Dotnet-Boxed/Templates#288]
The template includes the example of Car as a recommendation for the Command pattern. 

Have you considered having the unit test project in the template to promote the unit testing practice?

**Comment by RehanSaeed** [comment]
Yes, adding a unit test or actually an integration test project which uses the `WebApplicationFactory` api is something I've wanted to do. Would accept a PR for this.

**Comment by lamLeX** [comment]
@RehanSaeed Would you like to have unit test and integration test located in the same test project named `$projectName.Test.csproj`? Or would you like to have two separate projects `$projectName.UnitTest.csproj` and `$projectName.IntegrationTest.csproj"?
I prefer the later choice since it gives us two separate options that we can let the user to opt-out

**Comment by lamLeX** [comment]
Also, what test framework we should include? Or can it be user configurable via cli options?

**Comment by RehanSaeed** [comment]
With ASP.NET Core, I tend to write a lot of integration tests because they have made it so easy to start the app and make requests to it in memory. 

I like the names $projectName.UnitTest.csproj and $projectName.IntegrationTest.csproj. Each can be an option.

xUnit is the way to go. Very few people using .NET Core are using anything else.

**Comment by VictorioBerra** [comment]
I agree with all that. I do it the exact same way.

Some packages I use:

- https://github.com/fluentassertions/fluentassertions
- https://github.com/bchavez/Bogus
- https://github.com/moq/moq
- AutoFixture and friends https://github.com/AutoFixture/AutoFixture#downloads

**Comment by RehanSaeed** [comment]
I'm not sure I would include all of those by default except maybe Moq. For some reason I don't like FluentAssertions but I can see why others do. Bogus is cool but the danger is that your tests are not repeatable.

**Comment by VictorioBerra** [comment]
Yeah those are just suggestions. I use Bogus to seed my SQLIte DB and then I integration test against that. Bogus tries not to change the seed data, just dont update it to a major version or just stay on an older version and you will be fine. Still better than manually populating seed data.

**Comment by lamLeX** [comment]
@RehanSaeed Can you create a branch for this issue so that I can make a pull request to it directly from my branch? I want to make multiple pull requests to that branch so I can gather early feedback. Thanks,
For the time being, I made a pull request from my fork

**Comment by lamLeX** [comment]
Regarding the test framework, I used to think xUnit is nicer than NUnit. It's true if you compare with NUnit2. With NUnit 3 with their new [Constraint Model](https://github.com/nunit/docs/wiki/Constraint-Model), it is = xUnit+FluentAssertions.
This Constraint Assertion Model is technically similar to the fluent assertion. 

Anyway, I don't want to include too much tests that the user who wants to use this template ends up spending time cleaning it up.

I also thinking about changing the template so that the user can opt-out the Car example

**Comment by RehanSaeed** [comment]
If you look at the latest code. I added a new Orleans project template with integration test. As part of that work, I'm also adding an integration test to the other projects along with a solution and other files. Still work in progress to release those changes. Still also need to add more tests to it and add a unit test project too.

**Comment by VictorioBerra** [comment]
A little off topic but what was the motivation behind adding the Orleans
template?

**Comment by RehanSaeed** [comment]
I was learning it at a week long hack event at work, so I managed to put something together. It's a pretty cool piece of tech. Also, they don't currently have a `dotnet new` experience.

**Comment by VictorioBerra** [comment]
Sounds like a long week! Very cool though. Not sure we will ever dive into that here at work. Is it a replacement for Microservices? Does any client talk to the Orleans server?

**Comment by RehanSaeed** [comment]
Take a look at the ReadMe for it. I explained where I would use it there.

**Comment by RehanSaeed** [comment]
IntegrationTest projects were added to all project templates. Have fun!
