### ISSUE TITLE
Generated Swagger file is missing the host attribute

### ISSUE THREAD

**Issue by kmaneshk** [Dotnet-Boxed/Templates#306]
The generated swagger file is missing the host attribute. This can be easily set from the request's host attribute.

![image](https://user-images.githubusercontent.com/6300941/57207732-c21e5200-7012-11e9-9f72-41f03e76d4ca.png)

﻿**Which project template is the issue about?**

... ASP.NET Core API

**Which version of the project template is the issue about?**

...2019 Jan

**Which version of Visual Studio or the dotnet SDK were you using?**

...aspnet core 2.2

**Comment by RehanSaeed** [comment]
Merged. Thanks for your PR.
