### ISSUE TITLE
API version as constant

### ISSUE THREAD

**Issue by rkqiku** [Dotnet-Boxed/Templates#343]
https://github.com/Dotnet-Boxed/Templates/blob/6c8efa641d91cc3fee01523ba95c074a747c16ed/Source/Content/ApiTemplate/Source/ApiTemplate/Controllers/CarsController.cs#L19

**Comment by VictorioBerra** [comment]
Create a PR and we shall accept.

**Comment by rkqiku** [comment]
Is it better to have API version as a constant? Once we have a new API version, we change the constant instead of going through each controller

**Comment by VictorioBerra** [comment]
Not necessarily. You may version individual controller actions. Or you have version a new controller and keep the old. A constants would be a central hard coded location of all versions for example.

**Comment by rkqiku** [comment]
> Not necessarily. You may version individual controller actions. Or you have version a new controller and keep the old. A constants would be a central hard coded location of all versions for example.

How about this:
    public static class ApiVersionName
    {
        public const string FirstVersion = "1.0";
        public const string SecondVersion = "2.0";
        public const string ApiNamingConventionThirdVersion = "3.0";
    }

**Comment by VictorioBerra** [comment]
That's basically what I was thinking. Not every string needs to be a constant so it's up to you if you think we should.

**Comment by RehanSaeed** [comment]
Added `ApiVersionName.V1` constant. Thanks for the suggestion!
