### ISSUE TITLE
EnrichWithApolloTracing throws exception when there are errors in the result

### ISSUE THREAD

**Issue by tomecho** [Dotnet-Boxed/Templates#344]
﻿**Which project template is the issue about?**
GraphQL

**Which version of the project template is the issue about?**
Boxed Templates 2.1.1

**Which version of Visual Studio or the dotnet SDK were you using?**
VS19 16.1.5

EnrichWithApolloTracing throws exception when there are errors in the result.  I have fixed it by adding a null check on the result.Errors.  Also shown I have recorded the start time before executing the request.

![image](https://user-images.githubusercontent.com/2114323/61324515-9d97e080-a7e0-11e9-8c0f-fb52042ea1de.png)

**Comment by RehanSaeed** [comment]
Thank you @tomecho!

Added to front page as contributor.
