### ISSUE TITLE
Make Boxed.Templates.FunctionalTest a nuget package.

### ISSUE THREAD

**Issue by VictorioBerra** [Dotnet-Boxed/Templates#357]
I am writing my own templates, and I think it would be super helpful to have access to Boxed.Templates.FunctionalTest. So I can test my own custom API template in a similar way as you do.

Would this be possible?

**Comment by RehanSaeed** [comment]
Yes, I want to do this. It's a good idea.

Feel free to submit a PR to the Framework project to move the code. We can create a new `Boxed.DotnetNewTest` project (if you can think of a better name, I'm open to suggestions).

**Comment by VictorioBerra** [comment]
That name sounds great.
