### ISSUE TITLE
Why do we use a NuSpec file instead of a dotnet pack csproj file?

### ISSUE THREAD

**Issue by VictorioBerra** [Dotnet-Boxed/Templates#358]
https://docs.microsoft.com/en-us/dotnet/core/tools/custom-templates#packing-a-template-into-a-nuget-package-nupkg-file

I noticed we have a nuspec instead of using the .csproj pattern mentioned in the docs.

What is the reason for this?

**Comment by RehanSaeed** [comment]
These docs are new, I've never read them. Back when I wrote this, if this was possible I had no idea. Updated to use csproj now.
