### ISSUE TITLE
Alternatives to mutating the nuspec.

### ISSUE THREAD

**Issue by VictorioBerra** [Dotnet-Boxed/Templates#359]
https://github.com/Dotnet-Boxed/Templates/blob/master/Source/Boxed.Templates.nuspec#L5

If you run `cake -Target version` you will [mutate the nuspec](https://github.com/Dotnet-Boxed/Templates/blob/master/build.cake#L84).

That means, a developer could end up checking in the changed file unintentionally.

Is there a better way to do this? Maybe first copy off the file to a folder under .gitignore like "artifacts"?

**Comment by RehanSaeed** [comment]
Yes, I don't know why I implemented it like that. Now fixed.
