### ISSUE TITLE
build.cake test task is not dependent on build/restore yet it has flags to not restore or build

### ISSUE THREAD

**Issue by VictorioBerra** [Dotnet-Boxed/Templates#361]
https://github.com/Dotnet-Boxed/Templates/blob/a1cb93b3686fb6bbb6058821cbb7e1b402098874/build.cake#L51

Unless I am missing something, if you ran the cake task on its own without first building, it will not run any tests.

**Comment by VictorioBerra** [comment]
Actually, I get _why_ you wouldn't make it dependent. Because then its going to restore and build all over again.

I wish there was some way to have the best of both worlds.

If you run test again after making changed but not building, does it run the same binaries all over again but this time without your latest changes?

**Comment by RehanSaeed** [comment]
Cake has a `--Exclusive` flagto execute a single task. You can execute `dotnet cake` to run all tasks one after the other.
