### ISSUE TITLE
Kestrel is binding to the wrong port.

### ISSUE THREAD

**Issue by VictorioBerra** [Dotnet-Boxed/Templates#389]
When I run the app using the Kestrel launch config the console shows something like this:

```
[13:47:04 WRN] Overriding address(es) 'http://localhost:5000'. Binding to endpoints defined in UseKestrel() instead.
Hosting environment: Development
Content root path: C:\Source\redacted
Now listening on: http://[::]:80
```

This looks to me like calling UseKestreal is overriding the launch config.'

can you confirm?

**Comment by VictorioBerra** [comment]
Actually this is my fault. I renamed appsettings.json to appsettings.Development.json and then I renamed appsetting.Production.json to appsettings.json.

I didn't know ASPNETCORE_ENVIRONMENT defaulted to production when undefined. That's correct isn't it?

**Comment by RehanSaeed** [comment]
Yes, I found the same issue. It seems you have to have it this way around. If you find a way to make `appsettings.json` production and swich to `appsettings.Development.json`, I'd be really interested.

**Comment by VictorioBerra** [comment]
I'm sure you could just wrap it in a conditional check for IsDevelopment in your program.cs but that's extra boilerplate
