### ISSUE TITLE
Serilog only logging to File with version 3 of Serilog

### ISSUE THREAD

**Issue by bajmming** [Dotnet-Boxed/Templates#403]
I couldn't get Serilog to log to a file with the API template 2.2.0.  I upgraded Serilog.AspNetCore from 2.1.1 to 3.0.0 and this fixed the error.  Not sure if there was another way to get it to work, but the upgrade worked.

appsettings
```
"WriteTo": [
      {
        "Name": "Console",
        "Theme": "Code"
      },
      { "Name": "Debug" },
      {
        "Name": "File",
        "Args": { "path": "%TEMP%\\Logs\\example.txt" }
      }
    ]
```

![image](https://user-images.githubusercontent.com/2646044/65455013-69a10180-de9a-11e9-80ad-ab5b606001bc.png)

**Comment by VictorioBerra** [comment]
Is there more to your appsettings?

Im not sure what this could be, but I heard console ships with Serilog now by default. maybe the console include was missing before you updated?

**Comment by bajmming** [comment]
The appsettings is the out the box via the template, so the only bit I've added was the File sink.  The complete appsettings.js is below...
```
{
  "CacheProfiles": {
    // Cache static files for a year.
    "StaticFiles": {
      "Duration": 31536000,
      "Location": "Any"
    }
  },
  "Compression": {
    // Additional MIME types (other than the built in defaults) to enable response compression for.
    "MimeTypes": [
      "application/vnd.restful+json",
      "application/problem+json"
    ]
  },
  "ForwardedHeaders": {
    "AllowedHosts": [
      "*"
    ],
    "ForwardedHeaders": "XForwardedHost,XForwardedProto"
  },
  "Kestrel": {
    // Set stricter default limits to defend against various types of attacks.
    // See https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel#how-to-use-kestrel-in-aspnet-core-apps
    // And https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.server.kestrel.core.kestrelserverlimits
    "Limits": {
      "MaxRequestBodySize": 10240, // 10240 = 10KB. Default is 30MB. Use [RequestSizeLimit(100000000)] attribute to use more.
      "MaxRequestHeaderCount": 20 // Default is 100
    }
  },
  // Read more about configuring Serilog here https://github.com/serilog/serilog-settings-configuration
  "Serilog": {
    "MinimumLevel": {
      "Default": "Information",
      "Override": {
        "Microsoft": "Information",
        "System": "Information"
      }
    },
    "Enrich": [
      "FromLogContext",
      // Add full exception details using Serilog.Exceptions https://github.com/RehanSaeed/Serilog.Exceptions.
      "WithExceptionDetails",
      // Add the username and machine name to the logs using Serilog.Enrichers.Environment https://github.com/serilog/serilog-enrichers-environment.
      "WithEnvironmentUserName",
      "WithMachineName",
      // Add the process ID and name to the logs using Serilog.Enrichers.Process https://github.com/serilog/serilog-enrichers-process.
      "WithProcessId",
      "WithProcessName",
      // Add the current thread ID to the logs using Serilog.Enrichers.Thread https://github.com/serilog/serilog-enrichers-thread.
      "WithThreadId"
    ],
    "WriteTo": [
      {
        "Name": "Console",
        "Theme": "Code"
      },
      { "Name": "Debug" },
      {
        "Name": "File",
        "Args": { "path": "%TEMP%\\Logs\\example.txt" }
      }
    ]
  }
}


```

**Comment by VictorioBerra** [comment]
Looks like the console import is missing in there.

**Comment by bajmming** [comment]
Sorry do you mean the Console nuget was missing...not sure I quite understand?  My csproj only shows I've updated the single nuget package.  Let me know if you mean something else as I don't think my morning coffee has kicked in yet ;)

![image](https://user-images.githubusercontent.com/2646044/65458374-94428880-dea1-11e9-9c5b-f1ada8a7e3bf.png)

**Comment by VictorioBerra** [comment]
Unless I'm missing it, I dont see this anywhere
https://github.com/serilog/serilog-settings-configuration/blob/dev/sample/Sample/appsettings.json

Yes, the console nuget from serilog used to be required. But not anymore
https://github.com/serilog/serilog-aspnetcore/pull/110/files#diff-17f4b7600975565ad30f8375497d3c60R25-R30

You updated Serilog.AspNetCore which brought in console logger as a
dependency so everything started working again.

**Comment by bajmming** [comment]
Oh ok that makes sense.  I'm only using the appsettings that come with the Api template, and then I've just added File as an extra sink without the necessary config.  I'll have a look at that sample config link you sent as there might be some settings I want to bring into my project.  Thanks for the quick responses and I'll close this issue :)

**Comment by VictorioBerra** [comment]
Yeah I think that's an issue with our template.
