### ISSUE TITLE
Migrate Templates to Core 3

### ISSUE THREAD

**Issue by VictorioBerra** [Dotnet-Boxed/Templates#411]
This shouldn't be too bad, concerning the API template most work will be in our Program.cs because of the WebHostBuilder.

You may want to update all your Boxed.AspNetCore WebHostBuilderExtensions to use IHostBuilder and not WebHostBuilder.

**Comment by VictorioBerra** [comment]
This seems to work well actually

```csharp
        public static IHostBuilder CreateWebHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder => webBuilder
                        .UseIf(
                            x => string.IsNullOrEmpty(x.GetSetting(WebHostDefaults.ContentRootKey)),
                            x => x.UseContentRoot(Directory.GetCurrentDirectory()))
                        .UseIf(
                            args != null,
                            x => x.UseConfiguration(new ConfigurationBuilder().AddCommandLine(args).Build()))
                        .ConfigureAppConfiguration((hostingContext, config) =>
                            AddConfiguration(config, hostingContext.HostingEnvironment, args))
                        .UseSerilog()
                        .UseDefaultServiceProvider((context, options) =>
                            options.ValidateScopes = context.HostingEnvironment.IsDevelopment())
                        .UseKestrel(
                            (builderContext, options) =>
                            {
                                // Do not add the Server HTTP header.
                                options.AddServerHeader = false;


                                // Configure Kestrel from appsettings.json.
                                _ = options.Configure(builderContext.Configuration.GetSection(nameof(ApplicationOptions.Kestrel)));
                                ConfigureKestrelServerLimits(builderContext, options);
                            })
                        // Used for IIS and IIS Express for in-process hosting. Use UseIISIntegration for out-of-process hosting.
                        .UseIIS()
                        .UseStartup<Startup>());
```

**Comment by RehanSaeed** [comment]
There is actually a lot to do. Lots of changes and new features. I'm working on it. It will take a couple of weeks to do it all. Stay tuned.

**Comment by VictorioBerra** [comment]
Are you working in a branch so I can see what you're up to? I have been updating the apps I created with the templates and so far it hasn't been too bad. I just followed [the migration guide](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#prerequisites).

**Comment by VictorioBerra** [comment]
I see you're doing some work in the netcore3 branch. How is it going? Any blockers?

**Comment by RehanSaeed** [comment]
I think I'm done with Program.cs and the csproj files. The Orleans template is totally up to date and I'm happy with it. All framework code is also up to date now I think. This is what I plan to do in order.

- The Startup.cs classes for the API and GraphQL projects need a lot of work.
  - The API project needs to move to System.Text.Json, while GraphQL needs to configure Newtonsoft.Json somehow.
  - Going to switch CORS to use the middleware.
  - Need to switch from AddMvc to AddControllers in the API template. Need to see what this involves and how much code I can delete.
- I got all the swagger code building in the framework project and template itself but it's all broken as I'm using version 5 pre-release which is a big update.
- I also want to take this as an opportunity to switch to https://github.com/Dotnet-Boxed/Framework/issues/27 as you wished some time ago.
- GraphQL template needs a lot of care and attention. I'm not even sure it will work. I think I have to use a pre-release version of their packages.
- Also need to fix https://github.com/Dotnet-Boxed/Framework/issues/103.

Feel free to submit one or more small PR's to my netcore3 branch with any fixes. The last two in particular.

**Comment by VictorioBerra** [comment]
I am a complete noob at GraphQL, I will ping the author of #103 and see what the status is. Maybe I can do the PR for him if you're happy with his fix.

**Comment by RehanSaeed** [comment]
Anything would help. Thank you @VictorioBerra. I'm making slow progress.

**Comment by RehanSaeed** [comment]
Remaining Work:

- API template
  - [How to Write ISchemaFilter for ProblemDetails?](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/985). **Need help with this one**.
  - Upgrade to Serilog.AspNetCore's new middleware.
- GraphQL
  - Work out why it's not working.
  - Upgrade to Serilog.AspNetCore's new middleware.
- Orleans ✔

**Comment by santoshpatro** [comment]
@RehanSaeed : When will be the latest Dotnet Boxed GraphQL templates with .NET Core 3.0 available?

**Comment by RehanSaeed** [comment]
Soon

Kind Regards,

Muhammad Rehan Saeed
RehanSaeed.com

________________________________

**Comment by santoshpatro** [comment]
Thanks a lot Rehan. I am looking forward for it. I believe you need to do some video courses on this great subject and publish it in youtube :)

**Comment by RehanSaeed** [comment]
Merged to master. Release imminent today.

If I had time, I'd like to do some videos.
