### ISSUE TITLE
Compression not working on passing the header: Accept-Encoding:br

### ISSUE THREAD

**Issue by santoshpatro** [Dotnet-Boxed/Templates#426]
I installed the Dotnet-Boxed templates and then created a graphql project based on the templates. On validation using Postman I found that compression is not working as expected even though I pass the Accept-Encoding:br header in the request.

Can anyone help me to know how to fix this issue.

**Comment by RehanSaeed** [comment]
Compression will not work when using HTTPS due to security concerns. Where you using HTTPS?

**Comment by santoshpatro** [comment]
You are awesome Rehan. I re validated it with updating the code with **options.EnableForHttps = true** and found it working fine as expected.  I am trying the same with another graphql  based project but it is not working for me. Any help on this is much appreciated. Here goes the issue: 
https://stackoverflow.com/questions/58659506/response-compression-in-asp-net-core-2-2-not-working?noredirect=1#comment103626131_58659506

**Comment by santoshpatro** [comment]
Anyways the issue can be closed :)
