### ISSUE TITLE
Use GraphQL.Server.Authorization.AspNetCore instead of GraphQL.Authorization

### ISSUE THREAD

**Issue by lamLeX** [Dotnet-Boxed/Templates#450]
### Question

Relating to this issue https://github.com/graphql-dotnet/authorization/issues/11. 
Currently, the template reference GraphQL.Authorization and replicate the work done in this pull request
https://github.com/graphql-dotnet/server/pull/171

Should the template use the ASPNetCore version instead for the same reason that you discussed in graphql-dotnet/authorization/issues/11 ?

### Project template

GraphQL

**Comment by RehanSaeed** [comment]
Yes. I was the one that added that project.

However, it is unloved. There are changes that have been made to the non-ASP.NET Core one that have not also been made to the ASP.NET Core one. So, I don't really know. I need to compare the two again and decide. If you are interested, we need to make sure the two are up to date with changes and use the ASP.NET Core one.

**Comment by lamLeX** [comment]
I tried to swap the `GraphQL.Authorization` for `GraphQL.Server.Authorization.AspNetCore` and configure the policy via `AddAuthorization()` from `Microsoft.AspNetCore.Authorization` instead.
But the `AuthorizeWith()` does not pick up the policy. 
Do you have any documentation for how to substitute `GraphQL.Server.Authorization.AspNetCore` in place of `GraphQL.Authorization`?

**Comment by RehanSaeed** [comment]
I have no documentation.

Kind Regards,

Muhammad Rehan Saeed
RehanSaeed.com

________________________________

**Comment by RehanSaeed** [comment]
Closing this. The plan is not to switch from GraphQL-Dotnet to Hot Chocolate which is faster and has more features.
