### ISSUE TITLE
Add C# 8 Nullable Reference Types

### ISSUE THREAD

**Issue by RehanSaeed** [Dotnet-Boxed/Templates#505]
Add [C# 8 Nullable Reference Types](https://docs.microsoft.com/en-us/dotnet/csharp/nullable-references) to the following:

- [x] - The Framework NuGet Packages at https://github.com/Dotnet-Boxed/Framework.
- [x] - API Template
- [ ] - GraphQL Template - We are moving to the Hot Chocolate GraphQL server https://github.com/Dotnet-Boxed/Templates/pull/732, so this should be done as part of that move.
- [x] - Orleans Template
- [x] - NuGet Template - In this case it should be a template feature that we can turn on/off.

**Comment by gegaryfa** [comment]
I can pick up this issue if no one else is working on this.

**Comment by RehanSaeed** [comment]
Thanks for the offer @gegaryfa! I've updated the issue with a breakdown of what needs doing. Which of the above would you be interested in helping with?

**Comment by gegaryfa** [comment]
No problem. I can start with the `API Template` project and move on to another project once I have more free time.
