### ISSUE TITLE
ForwardedForHeaders not actually being configured.

### ISSUE THREAD

**Issue by VictorioBerra** [Dotnet-Boxed/Templates#609]
### Describe the bug
We are missing this in our program.cs
https://github.com/dotnet/aspnetcore/blob/master/src/DefaultBuilder/src/WebHost.cs#L241

More info https://devblogs.microsoft.com/aspnet/forwarded-headers-middleware-updates-in-net-core-3-0-preview-6/

### To Reproduce

Deploy a new API template to AAS Linux and check Request.IsHttps. It will be false.

### Expected behaviour

Deploy a new API template to AAS Linux and check Request.IsHttps. It should be true.

### Project template

API and maybe others.

## Environment

Latest VS, Core 3.1

**Comment by RehanSaeed** [comment]
We shouldn't need that, we configure the options in:

- https://github.com/Dotnet-Boxed/Templates/blob/435355945e58c00c491f9247aa3f0156a9649525/Source/ApiTemplate/Source/ApiTemplate/CustomServiceCollectionExtensions.cs#L103
- https://github.com/Dotnet-Boxed/Templates/blob/435355945e58c00c491f9247aa3f0156a9649525/Source/ApiTemplate/Source/ApiTemplate/appsettings.json#L25-L33

Are you saying that this is not working?

**Comment by VictorioBerra** [comment]
I couldnt get that to work. I think its because we dont do this: 

```
                        options.KnownNetworks.Clear();
                        options.KnownProxies.Clear();
```

maybe?

**Comment by RehanSaeed** [comment]
Could be. Can you give it a try?

**Comment by VictorioBerra** [comment]
Yes i will try in the next couple days and report back.

**Comment by VictorioBerra** [comment]
![image](https://user-images.githubusercontent.com/2934507/80105920-cce13800-853e-11ea-8be6-30be0d0917ea.png)

<hr />

### Steps for repo:

- In azure, create a new Linux AAS
- Set HTTPS Only in the TLS/SSL settings blade
- Click "download publish profile" in the top banner
- On your local machine, run `dotnet new api` you dont really need to specify any options. `-fh|--forwarded-headers` is true by default.
- Toss this into your Cars controller:

```csharp
[HttpGet("/IsHttps", Name = "IsHttps")]
public IActionResult IsHttps()
{
        return Ok(Request.IsHttps);
}
```

# Solution

Add this to Startup.cs

```csharp
services.Configure<ForwardedHeadersOptions>(options =>
{
        options.KnownNetworks.Clear();
        options.KnownProxies.Clear();
});
```

**Comment by RehanSaeed** [comment]
What if we added them to the JSON configuration?

```json
 "ForwardedHeaders": { 
   "AllowedHosts": [ 
     "example.com" 
   ], 
   "KnownNetworks": [],
   "KnownProxies": [],
   "ForwardedHeaders": "XForwardedFor,XForwardedHost,XForwardedProto" 
 }, 
```

**Comment by VictorioBerra** [comment]
@RehanSaeed Didnt work.

**Comment by VictorioBerra** [comment]
So options now I think are to add another method to `CustomServiceCollectionExtensions` or do this in Program.cs.

**Comment by RehanSaeed** [comment]
Looks like configuration is ignoring it because it is a complex type. Added:

```cs
                .Configure<ForwardedHeadersOptions>(
                    options =>
                    {
                        options.KnownNetworks.Clear();
                        options.KnownProxies.Clear();
                    })
```
