### ISSUE TITLE
Have you injected IConfiguration configuration, ILogger logger?

### ISSUE THREAD

**Issue by biapar** [Dotnet-Boxed/Templates#639]
### Question

Have you injected IConfiguration configuration, ILogger logger into startup and so usable into controllers api or class?
Thanks.

**Comment by VictorioBerra** [comment]
Please see code for that information.

Start up is here: https://github.com/Dotnet-Boxed/Templates/blob/master/Source/ApiTemplate/Source/ApiTemplate/Startup.cs

We take the "early initialization" approach as seen here https://github.com/serilog/serilog-aspnetcore/blob/dev/samples/EarlyInitializationSample/Program.cs

**Comment by biapar** [comment]
Thanks, but I don't understand with class you built to read appsettings into a controller.

**Comment by VictorioBerra** [comment]
That is done here https://github.com/Dotnet-Boxed/Templates/blob/master/Source/ApiTemplate/Source/ApiTemplate/CustomServiceCollectionExtensions.cs#L93

**Comment by biapar** [comment]
I create ConnectionString, but I'm not able to read into a class

```
public static IServiceCollection AddCustomOptions(
            this IServiceCollection services,
            IConfiguration configuration) =>
            services
                // ConfigureAndValidateSingleton registers IOptions<T> and also T as a singleton to the services collection.
                .ConfigureAndValidateSingleton<ApplicationOptions>(configuration)
                .ConfigureAndValidateSingleton<CompressionOptions>(configuration.GetSection(nameof(ApplicationOptions.Compression)))
                .ConfigureAndValidateSingleton<ForwardedHeadersOptions>(configuration.GetSection(nameof(ApplicationOptions.ForwardedHeaders)))
                .ConfigureAndValidateSingleton<CacheProfileOptions>(configuration.GetSection(nameof(ApplicationOptions.CacheProfiles)))
                .ConfigureAndValidateSingleton<KestrelServerOptions>(configuration.GetSection(nameof(ApplicationOptions.Kestrel)))
              .ConfigureAndValidateSingleton<ConnectionStringsOptions>(configuration.GetSection(nameof(ApplicationOptions.ConnectionStringsOptions)))
            ;
```

**Comment by VictorioBerra** [comment]
What does ConnectionStringsOptions look like? And what does your appsettings and appsettings.Development look like? Make sure to redact any secrets.

**Comment by biapar** [comment]
> What does ConnectionStringsOptions look like? And what does your appsettings and appsettings.Development look like? Make sure to redact any secrets.

That is?
