### ISSUE TITLE
ProducesResponseType to be part of box template

### ISSUE THREAD

**Issue by nileshsawant80** [Dotnet-Boxed/Templates#640]
SwaggerResponse is removed in more recent versions of Swashbuckle.AspNetCore. ProducesResponseType is the way to go, with optional XML comments if you still want the string explanation (read more about that here)

Template needs to be updated to include ProducesResponseType asp.net code mvc attribute

**Comment by RehanSaeed** [comment]
It still exists in `Swashbuckle.AspNetCore.Annotations`. It's a separate NuGet package.

**Comment by jgenard** [comment]
Why is SwaggerResponse retained in favor of ProducesResponseType that is part of the basic packages offered by Microsoft ? Is there a reason behind this choice ?

**Comment by RehanSaeed** [comment]
@jgenard This is a good question. A couple of reasons:

1. `SwaggerResponse` also allows you to specify a description. The alternative is to use a non-standard XML comment syntax which has no type checking.
2. I'm trying to add `ContentType` to `SwaggerResponse` in https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/1956. This will make the response finally fully documented.

**Comment by jgenard** [comment]
Thanks for your quick answer ! And thanks for your hard work.
