### ISSUE TITLE
Release NuGet Package from GitHub Actions

### ISSUE THREAD

**Issue by RehanSaeed** [Dotnet-Boxed/Templates#670]
Currently the NuGet package template only pushes the NuGet package from the Azure Pipelines CI build. We should also do this from GitHub Actions since this is now the future of where Microsoft is investing.

**Comment by VictorioBerra** [comment]
Are we pushing from both? Or just cutting over to push only from Actions and not Pipelines?

**Comment by RehanSaeed** [comment]
I've heard that Microsoft is putting all it's effort into GitHub as opposed to Azure DevOps.

I'd like to add the ability to do it from either GitHub Actions or Azure Pipelines in the NuGet template, so you can choose.

Later on, I might even switch this repo and my other personal ones to use GitHub Actions instead.

**Comment by VictorioBerra** [comment]
I heard similar on Twitter but I think they put their focus into new features and enhancements into Actions, development in Azure DevOps is still very active.

I would do the same but I have on-prem deployment agents that I have to use to poll for releases and deploy to on-prem IIS servers behind firewalls.

My personal stuff though I deploy from DevOps to places like AWS S3.

I am eager to hear more about the new static site hosting https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-static-website

And this https://twitter.com/amandaksilver/status/1263312696620941314
