### ISSUE TITLE
Switch from GraphQL.NET to Hot Chocolate

### ISSUE THREAD

**Issue by RehanSaeed** [Dotnet-Boxed/Templates#686]
Hot Chocolate is the new hotness. I have a week of dev time coming up to get this implemented.

**Comment by lamLeX** [comment]
Hi @RehanSaeed,
Thank you for all your hard works making these templates for us. 
May I have a status update of this ticket?
Would you accept a PR for this?

**Comment by RehanSaeed** [comment]
I'm currently on paternity leave and will be back in the next couple of weeks.

There were some issues with converting to Hot Chocolate v10.

- [ ] - Finish adding an example of paging with a data loader.
- [ ] - Add subscriptions.
- [ ] - If I'm using a `NodeResolver`, there doesn't seem to be a way to move that code to a separate class, like you can with a standard resolver. I think this is coming in v11 but need to confirm.
- [ ] - Use automatic relay input type (See https://github.com/ChilliCream/hotchocolate/issues/773).
- [ ]  - Set custom playground and voyager URL's (See https://github.com/ChilliCream/hotchocolate/issues/1203).

v11 fixes a lot of issues and I think makes some breaking changes. I am considering updating this PR to use the preview v11 packages. If you'd like to help, please feel free to raise a PR for this branch.

**Comment by lamLeX** [comment]
@RehanSaeed Congratulation on your new family member!!!
I'll look into your pending branch to see if I could continue with that.
Cheers

**Comment by RehanSaeed** [comment]
Fixed by https://github.com/Dotnet-Boxed/Templates/pull/732

**Comment by RehanSaeed** [comment]
Further improvements are listed in https://github.com/Dotnet-Boxed/Templates/issues/1022
