### ISSUE TITLE
Push to Github packages doesn't work

### ISSUE THREAD

**Issue by sharok** [Dotnet-Boxed/Templates#755]
### Describe the bug

`Dotnet NuGet Push` step in the `Push GitHub Packages` completes with the error. 

```
Run $count = 0;
  $count = 0;
  do {
      ++$count;
      dotnet nuget push .\windows-latest\*.nupkg --source GitHub --skip-duplicate;
  }
  while ($count -lt 30 -and $LastExitCode -ne 0)
  shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"
  env:
    DOTNET_NOLOGO: true
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_CLI_TELEMETRY_OPTOUT: true
    MINVERBUILDMETADATA: build.4
warn : No API Key was provided and no API Key could be found for 'https://nuget.pkg.github.com/sharok'. To save an API Key for a source use the 'setApiKey' command.
Pushing testnuget.0.0.0-preview.0.3.nupkg to 'https://nuget.pkg.github.com/sharok'...
  PUT https://nuget.pkg.github.com/sharok/
  NotFound https://nuget.pkg.github.com/sharok/ 192ms
error: Response status code does not indicate success: 404 (Not Found).
```

### To Reproduce
Just created a project to test and didn't make any changes except in `matrix.os` to build on windows only.

### Project template
Nuget template.  Have no idea how to check the installed version, but it latest.  Installed today.

## Environment
VS: 2019
SDK: 3.1.401

**Comment by GeeWee** [comment]
I still have this issue even with `DOTNET_SYSTEM_NET_HTTP_USESOCKETHANDLER` set to 0: Just created the project today, and the build.yml looks like this:
```yaml
		env:
          DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER: 0
        run: |
          $count = 0;
          do {
              ++$count;
              dotnet nuget push .\windows-latest\*.nupkg --source GitHub --skip-duplicate;
          }
          while ($count -lt 1000 -and $LastExitCode -ne 0)
        shell: pwsh
```
Also getting the same errors
```
warn : No API Key was provided and no API Key could be found for 'https://nuget.pkg.github.com/GeeWee'. To save an API Key for a source use the 'setApiKey' command.
Pushing FastestNuGet.0.0.0-preview.0.2.nupkg to 'https://nuget.pkg.github.com/GeeWee'...
  PUT https://nuget.pkg.github.com/GeeWee/
  NotFound https://nuget.pkg.github.com/GeeWee/ 903ms
error: Response status code does not indicate success: 404 (Not Found).
```

I realize the issue is not on dotnet-boxed's end. I just wanted to clarify that setting `DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER` does not sufficiently solve the problem

**Comment by RehanSaeed** [comment]
I'm leaning towards trying the https://github.com/jcansdale/gpr tool instead. GitHub/NuGet don't seem interested in fixing the problem.

**Comment by RehanSaeed** [comment]
GitHub have done something to make it much more reliable. It's still not 100% but fails a lot less. So I say we stick to the current workaround of trying 1000 times to push the package until it gets fixed completely.

**Comment by GeeWee** [comment]
I can confirm that before I was unable to publish to github, it now succeeds (still after a bunch of tries though)

**Comment by RehanSaeed** [comment]
GitHub have finally fixed the issue. Going back to a standard `dotnet nuget push` command in this PR https://github.com/Dotnet-Boxed/Templates/pull/828
