### ISSUE TITLE
StyleCop missing from Directory.Build.Props by default.

### ISSUE THREAD

**Issue by VictorioBerra** [Dotnet-Boxed/Templates#758]
### Describe the bug

StyleCop missing from Directory.Build.Props when you do not specify `-stc`.

### To Reproduce

`dotnet new api --name "StyleCopTest1"`

VS

`dotnet new api --name "StyleCopTest2" -stc`

### Expected behaviour

Directory.Build.Props should have `<PackageReference Include="StyleCop.Analyzers" PrivateAssets="all" Version="1.1.118" Condition="'$(StyleCop)' == 'true'" />`

### Project template

API (maybe others)

## Environment

401

**Comment by RehanSaeed** [comment]
StyleCop is turned off by default. That line is already in the code for the API template.

Am I missing something?

**Comment by VictorioBerra** [comment]
Ah just looked, you are right but `dotnet new api --help` shows style cop is **true** by default.

![image](https://user-images.githubusercontent.com/2934507/91983555-79070c80-ecf1-11ea-8327-7e2b1cc2b9de.png)

**Comment by RehanSaeed** [comment]
Raised bug in https://github.com/dotnet/templating/issues/2492.

**Comment by RehanSaeed** [comment]
I think we can close this. The star seems to have a different meaning in the .NET CLI. It's up to them to fix it.
