### ISSUE TITLE
[DOCUMENTATION] Confusing reference to pfx file in Nuget template

### ISSUE THREAD

**Issue by GeeWee** [Dotnet-Boxed/Templates#795]
### Describe the bug

The nuget seems to have a reference to a pfx file that is either misleading or confusing
![image](https://user-images.githubusercontent.com/6381792/94702001-90133b80-033d-11eb-9089-5737f8e5fd96.png)

Looking [at the repository](https://github.com/Dotnet-Boxed/Templates/search?q=pfx), the only reference to a pfx file is in a build task that is not involved in the nuget, and gitignore files.

Three potential scenarions:
- The pfx file should refer to the .snk file
- The pfx file comment is a leftover and should be deleted
- The pfx file refers to something I don't know. In this case we should provide a link where the user can learn more.

### Project template

Nuget - version is the latest on the main branch where the documentation is.

**Comment by RehanSaeed** [comment]
You are correct, the pfx should refer to the snk file.

**Comment by GeeWee** [comment]
That makes sense. Thanks for fixing it!
