### ISSUE TITLE
Switch default branch name to main

### ISSUE THREAD

**Issue by GeeWee** [Dotnet-Boxed/Templates#798]
### Describe the feature

Seeing as Github will from [1st of october (today!)](https://github.com/github/renaming) use `main` as the default branch name, rather than master, Dotnet-boxed does the same.

After migrating one project from master to main by hand, there's a few things that needs to be done (such as e.g. changing the branch on the badges)

It might also be worth changing some of the third party documentation (e.g. blog posts) to reflect this change.

I would be willing to try submitting a PR for this change, if you would accept it.

### Project template
I know it's true for the Nuget package, and I assume it is for the others as well.

**Comment by RehanSaeed** [comment]
This has been on my TODO list but is a major breaking change. I'd accept a PR for it.

**Comment by RehanSaeed** [comment]
I'm going to go ahead with the rename.

cc @VictorioBerra 

More info here:
https://www.hanselman.com/blog/easily-rename-your-git-default-branch-from-master-to-main

**Comment by VictorioBerra** [comment]
Looks easy enough! Any of the CICD scripts mention master? Like the triggers?

**Comment by GeeWee** [comment]
Yeah go ahead. Unfortunately I didn't have the time to do it as soon as I had hoped.
I have done the work on a Nuget repository created from Dotnet-boxed where I manually renamed master to main. If I remember correctly the things that mention master are:
- The CI/CD triggers
- The readme badges

I don't think there is more than that, but it has been a while.
