### ISSUE TITLE
previousPageUrl in ASP.NET Core API template always return first page

### ISSUE THREAD

**Issue by cuno92** [Dotnet-Boxed/Templates#800]
### To Reproduce

Get previousPageUrl (data of Get Api at page 3)

### Expected behaviour

Return page 2

### Project template

4.8.0

## Environment

3.1.402

**Comment by VictorioBerra** [comment]
Duplicate? https://github.com/Dotnet-Boxed/Templates/issues/783

**Comment by cuno92** [comment]
> Duplicate? #783

Thanks @VictorioBerra  , i will close this bug
