### ISSUE TITLE
[GraphQL]Removal of InstrumentingGraphQLExecutor and InstrumentFieldsMiddleware

### ISSUE THREAD

**Issue by lamLeX** [Dotnet-Boxed/Templates#815]
### Describe the bug

We are trying to upgrade the project to use `GraphQL 3.0.0.2026` together with `GraphQL.Server.Transports.AspNetCore 4.0.1`
It seems like in the latest version they have implemented the code in  [Source/GraphQLTemplate/Source/GraphQLTemplate/InstrumentFieldsMiddleware.cs](https://github.com/Dotnet-Boxed/Templates/blob/master/Source/GraphQLTemplate/Source/GraphQLTemplate/InstrumentFieldsMiddleware.cs) (ref [GraphQL/Instrumentation/InstrumentFieldsMiddleware.cs](https://github.com/graphql-dotnet/graphql-dotnet/blob/3.0.0/src/GraphQL/Instrumentation/InstrumentFieldsMiddleware.cs)) and [GraphQLTemplate/InstrumentingGraphQLExecutor.cs](https://github.com/Dotnet-Boxed/Templates/blob/master/Source/GraphQLTemplate/Source/GraphQLTemplate/InstrumentingGraphQLExecutor.cs) (ref [Core/Internal/DefaultGraphQLExecuter.cs#L50](https://github.com/graphql-dotnet/server/blob/4.0.1/src/Core/Internal/DefaultGraphQLExecuter.cs#L50) and [Core/Internal/DefaultGraphQLExecuter.cs#L77](https://github.com/graphql-dotnet/server/blob/4.0.1/src/Core/Internal/DefaultGraphQLExecuter.cs#L77)

Without removing this code from the old template, we ran into DI where the `InstrumentFieldsMiddleware` is not registered properly.

I understand that you may no longer want to maintain the template with graphql-dotnet anymore and planning to switch to hotchocolate (#686) 
This bug should be documented somewhere in case people who used the old template want to upgrade to `GraphQL 3.0.0.2026` together with `GraphQL.Server.Transports.AspNetCore 4.0.1`

### Project template

GraphQL

**Comment by RehanSaeed** [comment]
Thanks @lamLeX! This may help others.

We are currently working on switching over to Hot Chocolate but are waiting for v11 for that to complete. In the mean time, I don't have plans to upgrade to GraphQL v3 unless someone wants to submit a PR and it's very simple to do.
