### ISSUE TITLE
Should we add WithExposedHeaders("WWW-Authenticate") to cors policy?

### ISSUE THREAD

**Issue by VictorioBerra** [Dotnet-Boxed/Templates#816]
### Describe the feature

https://github.com/IdentityServer/IdentityServer4/blob/9fa8eafdeaca8dc60953cebb5a215a86701828b0/samples/Clients/src/APIs/SimpleApi/Startup.cs#L43

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/WWW-Authenticate

### Project template

All

**Comment by RehanSaeed** [comment]
It's only relevant if you have auth right? You might not want auth on your API. Even then I've not come across this HTTP header and am not entirely sure what it's for.
