### ISSUE TITLE
Possible issue with Web.Config

### ISSUE THREAD

**Issue by VictorioBerra** [Dotnet-Boxed/Templates#818]
### Describe the bug

In the API template, both the web and test project target `<Project Sdk="Microsoft.NET.Sdk.Web">` this makes them both web projects in the eyes of dotnet. When I publish, I get a Web.Config like this:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <location path="." inheritInChildApplications="false">
    <system.webServer>
      <handlers>
        <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModuleV2" resourceType="Unspecified" />
      </handlers>
      <aspNetCore processPath="dotnet" arguments=".\MyApp.IntegrationTest.dll" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" hostingModel="inprocess" />
    </system.webServer>
  </location>
</configuration>
<!--ProjectGuid: 57839160-3C89-4A5A-BC23-A78F39551C1E-->
```

Emphasis on: `arguments=".\MyApp.IntegrationTest.dll"`

### To Reproduce

Create a template with integration tests, publish, check Web.Config, it might produce one like the above. It did for my anyway.

### Project template

API

## Possible Solutions

- Be more explicit about which project to publish in CAKE.
- `<IsPackable>false</IsPackable>` and `<IsPublishable>false</IsPublishable>`

**Comment by faviann** [comment]
In my case to make it publishable I had to add the following to the project.
```
<PropertyGroup>
  <IsPublishable>false</IsPublishable>
  <IsWebConfigTransformDisabled>true</IsWebConfigTransformDisabled>
</PropertyGroup>
```

Without 'IsWebConfigTransformDisabled' set to true, the target 'TransformWebConfig' during publish would fail because it was expecting a web.config file in the publish folder of the IntegrationTest project.  Not sure why yet (didn't have time to investigate more) but I'm posting the fix in case somebody else encounters the issue.

I can push a PR with the fix if wanted. I didn't yet because I was unsure if that my fix was the best approach.

**Comment by VictorioBerra** [comment]
I think that is duct tape IMO. Publish is still wrong, its publishing IntegrationTest first still, which it should not be. It shouldn't be trying to publish this at all. Maybe related? https://github.com/dotnet/sdk/issues/12196

A few more things to look into, `dotnet publish` and the `dotnet cake` seem to work differently. Does `dotnet publish` work or am I crazy? Maybe its the clean that happens in `dotnet cake` because that way the Web.Config is wiped every time.

Lastly, I think the best solution is to edit the cake file and explicitly publish the web project. Instead of publishing the whole solution. The core of this issue is that the test project targets the web SDK (rightfully so).

**Comment by VictorioBerra** [comment]
> So my gut feeling is that, to really fix the issue, I'll have to make a PR fixing the _TransformWebConfig Target of the dotnet.sdk?

Yeah I think in the long run that is the best solution. Nice job tracing down the logging and actual target calls.

When building twice, the second succeeds because the Web.Config exists thanks to the first build. Running cake without a target will clean, restore, build, test and publish.

Lastly, to fix it this on our side, I think the best solution is to edit the Cake file and be more explicit about publishing the primary web project. Any cons to this? Most people aren't publishing unrelated projects in the same solution right?

**Comment by RehanSaeed** [comment]
- Adding `<Project Sdk="Microsoft.NET.Sdk.Web">` to the integration tests is required as indicated in [the docs](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-3.1#test-app-prerequisites).
- xUnit adds `<IsPackable>false</IsPackable>` for you https://github.com/xunit/xunit/issues/1520.

As far as publishing goes if you are running the `Publish` task in the cake script, I see your point. It's currently publishing all projects in the solution. There are two ways to solve this problem:

1. In the cake scripts publish step, only publish projects in the `/Source` subdirectory.
2. Add `<IsPublishable>false</IsPublishable>` to the integration test.

I'm leaning towards the first one. Does that solve your issue or have I missed something?

**Comment by VictorioBerra** [comment]
The first one will fix it. The second option is bugged. The bug will still try and transform the Web.Config even though its not being published.

We should go with the first option.

**Comment by faviann** [comment]
It did fix the issue. Thanks! (Sorry for the late answer)
