### ISSUE TITLE
Maybe an issue in net5.0 Startup.ConfigureServices seems to be called twice

### ISSUE THREAD

**Issue by VictorioBerra** [Dotnet-Boxed/Templates#864]
I think something maybe changed with Mvc Testing Server as I noticed `Startup.ConfigureServices` gets called twice when I change the taregt framework to .NET5.0 from netcoreapp3.1.

This is causing issues because we have a TestStartup that overrides and calls ConfigureServices as well.

**Comment by RehanSaeed** [comment]
Going to fix this in https://github.com/Dotnet-Boxed/Templates/pull/865

**Comment by RehanSaeed** [comment]
https://github.com/dotnet/aspnetcore/issues/26487
