### ISSUE TITLE
MaxRequestHeaderCount 20 is way too low.

### ISSUE THREAD

**Issue by VictorioBerra** [Dotnet-Boxed/Templates#867]
https://github.com/Dotnet-Boxed/Templates/blob/772580aa415333feb0aa2fa9d575daf20a1d33d7/Source/ApiTemplate/Source/ApiTemplate/appsettings.json#L61

I have built quite a few Boxed APIs and delivered them to production and almost every time I get an issue where this is too low and the requests are dropped. It took verbose logging to uncover. Can/should we bump this?

**Comment by RehanSaeed** [comment]
What's a good number?

**Comment by VictorioBerra** [comment]
Doubling it to 40 would be reasonable. A big reason for this is cookies. We have tons of sites on www.mydomain.com/virtualsite* so I think the cookies header payload grows a bit over time.

**Comment by RehanSaeed** [comment]
Fixed in https://github.com/Dotnet-Boxed/Templates/pull/865.
