### ISSUE TITLE
Separating server code and business code into two separate csproj

### ISSUE THREAD

**Issue by lamLeX** [Dotnet-Boxed/Templates#970]
### Describe the feature
The Boxed templates is a great starting template to get started with a ASP.net core app.
Currently in the api template, the code for configuring ASP.Net core server (eg. setup Cors, hsts, serilog, healthcheck, etc.) and the business code (e.g. Swagger for rest api, the car examples, starwar example, commands, repositories, etc) are in the same project. This is simple yet have a few downsides. One of those comes when a project started with this template requires an upgrade (e.g. from netcore 2.2 to 3.1 and so on). I have a few projects started with this template when it was using .netcore 2.2. Since 2.2 has reached the end of life, we need to upgrade to at least 3.1. Because business code resides together with the server setup code, comparing the code for upgrading to the latest version of boxed template requires to selectively chose the file for comparison(e.g. `MvcBuilderExtensions.cs`, `ProjectServiceCollectionExtensions.cs`). This is quite a hassle in the case we need to investigate to determine which code is addition code specific to the business logic and which code has been removed from the boxed template. For example, in one of my projects we have a custom code to add support for request example https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters#request-example. If the person who does the upgrade wasn't familiar with Boxed Template, when comparing the new Boxed template with existing project, he may remove the request example feature by accident. Another example is `CorrelationId` which included in the older version of Boxed Template has been removed in the newer version. Again, if the person who does the upgrade isn't familiar with Boxed Template, he may retain the feature which may have been replaced with the better alternatives. 

I solved this issue by keeping the server setup as a shell project that only contains server setup code (e.g. Cors, hsts, healthcheck).
This project will be the entry point and reference a library which contains business code (e.g swagger, graphql). This business code will be added to IOC of the shell project as extension calls such as `AddProjectCommands`, `AddProjectRepositories` or just a single extension `AddRestApi` which calls all above extensions.
The benefit for this approach is that we could isolate and communicate clearly which code is a part of boxed template and which code relates to business. When we want to upgrade the boxed template, we only need to compare the shell project as a whole and exclude the business logic code. Also the shell projects could be the same across other templates (e.g. rest swagger, graphql, etc.) later you could use this shell project for other template such as blazor wasm hosted with ASP.NET core. 

If you agree to this suggestion, I volunteer myself to refactor the template to support this scenario.

### Project template
API and graphql

**Comment by RehanSaeed** [comment]
@lamLeX Thanks for your comment and your offer of help!

## Split csproj Files

Regarding splitting up into multiple `csproj` files, the philosophy of this project is to:

> provide the minimum amount of code required to get you going faster.

While we could split the projects, there would also be a lot of people who don't find it necessary and might get scared off by the extra complexity. We could also make it an option, which would be my preferred approach. However, in this case the option would probably be very difficult to maintain. I believe `dotnet new` based templates have the ability to move files. I haven't used that feature yet but I think it could be done.

## CorrelationId

Regarding `CorrelationId`, I recommend using the Open Telemetry feature (See my [blog series](https://rehansaeed.com/deep-dive-into-open-telemetry-for-net/)) instead which adds a kind of correlation ID HTTP header and a lot more. However, setting up Open Telemetry is not that straight forward as compared to the `CorrelationId` package so you can continue to use that instead if you choose.

## Updating your Project

This is difficult. I understand that `dotnet new` will in future provide some method of keeping a project built from a template up to date but that is a long way off and I can't imagine how that will work.

My recommendation is to register for GitHub release notifications, so when we make changes and release them, you get links to all PR's and can decide whether you need to update any of your code.

**Comment by lamLeX** [comment]
@RehanSaeed 
### Re: Spliting csproj files and updating project created from template
Your reply prompts me to think in a different direction. Maybe instead of including the configuration code such as `AddCustomMvcOptions`, `AddCustomOptions`, etc. in the template, we should move all those code into `Boxed.AspNetCore` library the same way you have done with `AddServerTiming`.  So in the template's `ConfigureServices`, instead of 
```C#
services
#if ApplicationInsights
   // Add Azure Application Insights data collection services to the services container.
  .AddApplicationInsightsTelemetry(this.configuration)
#endif
// abbreviate the rest for brevity
   ...
  .Services
```

We should have have an extension like this in `Boxed.AspNetCore`
```C#
public static IServiceCollection AddBoxedTemplateApi(this IServiceCollection services, IConfiguration configuration)
=>
  services
    .AddIf(configuration.GetSection("ApplicationInsights").Exists(), s=>s.AddApplicationInsightsTelemetry(this.configuration))
//abbreviate the rest for brevity
    ....
    .Services
```
The template's `ConfigureServices` will become simplified as `services.AddBoxedTemplateApi(this.configuration)`
and in the template's `application.json` we still have this section 
```JSON
  //#if (ApplicationInsights)
  "ApplicationInsights": {
    // The instrumentation key for Application Insights retrieved from Azure e.g. 11111111-2222-3333-4444-555555555555
    "InstrumentationKey": "APPLICATION-INSIGHTS-INSTRUMENTATION-KEY"
  },
  //#endif
```
Taking this approach, we make the boxed template extremely configurable and up-gradable via ASP.Net core configuration API. 
Most of the time when I created a project using `dotnet new api`, if I missed a flag, I need to do run the cli again to get the code I want. If we shift to use Asp.net core configuration API, we will be more flexible in toggling a feature. This will make it easier to upgrade as you could maintain the feature via the `Boxed.AspNetCore` rather via the template.


### Re: CorrelationId
Your blog series is very insightful and I'm following it as we are investigating to standardize the use of OpenTelemetry and ApplicationInsight in our project.

**Comment by RehanSaeed** [comment]
There is a very hard trade-off between flexibility and upgradeability. I think we should prefer the former, since we have no idea what people want to use the project template for. However, I see why some people want something simpler to upgrade. I'm hoping the `dotnet new` feature I talked about to help with upgrades will help solve that issue in the future.

**Comment by RehanSaeed** [comment]
Closing for now. Feel free to reopen if you have more to add.
