### ISSUE TITLE
API project failed to start with `dotnet` command

### ISSUE THREAD

**Issue by lamLeX** [Dotnet-Boxed/Templates#975]
### Describe the bug

Project created with boxed API couldn't be launched via `dotnet` command (e.g. `dotnet new50.dll`) . Running the application via `dotnet run` is fine.

### To Reproduce

Build the project using `dotnet build`.
Go to `bin` folder and try to launch either `new50.exe` or `dotnet new50.dll`
The application failed to start, no log is produced 
![image](https://user-images.githubusercontent.com/4281894/108576354-271f6680-72d2-11eb-9fa4-14f9b01e9026.png)

### Expected behaviour

I started a new project using default VisualStudio template, build and run the application with dotnet command. The application started, accepted requests and printed out log

![image](https://user-images.githubusercontent.com/4281894/108576831-ddd01680-72d3-11eb-85e5-9bb8c9438574.png)

### Project template

API Template

## Environment

```
PS D:\Projects> dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.103
 Commit:    72dec52dbd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.103\

Host (useful for support):
  Version: 5.0.3
  Commit:  c636bbdc8a

.NET SDKs installed:
  2.2.207 [C:\Program Files\dotnet\sdk]
  3.1.406 [C:\Program Files\dotnet\sdk]
  5.0.102 [C:\Program Files\dotnet\sdk]
  5.0.103 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by RehanSaeed** [comment]
When you run like that, you run the application in Production mode. If you look in `Program.cs`, you will see the following code which turns off console logging in production mode. It's up to you as a developer to decide where you want your logs to go in production mode as there are too many choices for us a template authors to decide for you.

```cs
                .WriteTo.Conditional(
                    x => hostEnvironment.IsDevelopment(),
                    x => x.Console().WriteTo.Debug())
```

When you turn on console logging, you will see that it's not finding the `appsettings.json` file. This is because you are not running the dotnet command from the correct directory. If you run like this, it will find the appsettings.json file in the current directory and it should work:

```powershell
cd D:\Projects\new50\Source\new50\bin\Debug\net5.0
dotnet new50.dll
```

In addition, there was the possibility of a `NullReferenceException` in production mode when there is a missing `appsettings.json` file which is addressed in https://github.com/Dotnet-Boxed/Templates/pull/983.
