### ISSUE TITLE
using -it false to omit generating integration tests breaks the build

### ISSUE THREAD

**Issue by oising** [Dotnet-Boxed/Templates#982]
The solution generated still tries to build the non-existent integration project:

```
dotnet new api --title "API1" -an "Application Insights" -ga false -it false -htp 6000 -ot true -cp Azure
```

![image](https://user-images.githubusercontent.com/1844001/109101287-727fad80-76f4-11eb-94bb-b5832429f717.png)

**Comment by RehanSaeed** [comment]
There was a `Tests` directory and integration test project which were removed from the directory but we failed to remove them from the solution, this is now fixed in https://github.com/Dotnet-Boxed/Templates/pull/985.
